x-environment: &shopware
  environment:
    APP_ENV: prod
    DATABASE_URL: 'mysql://shopware:shopware@database/shopware'
    DATABASE_HOST: 'database'
    APP_URL: ${APP_URL:-http://127.0.0.1:8000}
    APP_SECRET: 'def0000049e2f8d3fee13759c3e9f9062414e4f88df3fe9aea4aa13d2ddc994600149ee8b77d900e6b2f1730c21fe2307407b64217e6ddbc4c86f834bcac26b2f0a9d789'
    PHP_SESSION_HANDLER: redis
    PHP_SESSION_SAVE_PATH: 'tcp://cache:6379/1'
  volumes:
    - files:/var/www/html/files
    - theme:/var/www/html/public/theme
    - media:/var/www/html/public/media
    - bundles:/var/www/html/public/bundles
    - thumbnail:/var/www/html/public/thumbnail
    - sitemap:/var/www/html/public/sitemap
    - apps:/var/www/html/custom/apps
    - plugins:/var/www/html/custom/plugins
    - vendor:/var/www/html/vendor

services:

  database:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: shopware
      MARIADB_USER: shopware
      MARIADB_PASSWORD: shopware
      MARIADB_DATABASE: shopware
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-pshopware" ]
      timeout: 20s
      retries: 10
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.tcp.services.shopware-db-tcp.loadbalancer.server.port=3306"

  init-perm:
    image: alpine
    <<: *shopware
    command: chown 82:82 /var/www/html/files /var/www/html/public/theme /var/www/html/public/bundles /var/www/html/public/media /var/www/html/public/thumbnail /var/www/html/public/sitemap /var/www/html/custom/apps /var/www/html/custom/plugins /var/www/html/vendor
    networks:
      - dokploy-network
  init:
    image: local
    <<: *shopware
    build:
      context: .
    entrypoint: [ "php", "vendor/bin/shopware-deployment-helper", "run" ]
    depends_on:
      database:
        condition: service_healthy
      init-perm:
        condition: service_completed_successfully
    networks:
      - dokploy-network
  web:
    image: local
    <<: *shopware
    build:
      context: .
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - dokploy-network

  worker:
    image: local
    <<: *shopware
    restart: unless-stopped
    build:
      context: .
    volumes_from:
      - init
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint: [ "php", "bin/console", "messenger:consume", "async low_priority", "--time-limit=300", "--memory-limit=512M" ]
    deploy:
      replicas: 3
    networks:
      - dokploy-network
  scheduled-task:
    image: local
    <<: *shopware
    restart: unless-stopped
    build:
      context: .
    volumes_from:
      - init
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint: [ "php", "bin/console", "scheduled-task:run" ]
    networks:
      - dokploy-network
  cache:
    image: valkey/valkey:latest
    networks:
      - dokploy-network
      
  adminer:
    image: adminer
    restart: always

volumes:
  mysql-data:
  files:
  theme:
  media:
  thumbnail:
  sitemap:
  apps:
  plugins:
  vendor:
  bundles:
networks:
  dokploy-network:
    external: true